Myblog1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from rest_framework.routers import DefaultRouter

from storm.sitemaps import ArticleSitemap, TagSitemap, CategorySitemap
from api import views as api_views
if settings.API_FLAG:
    router = DefaultRouter()
    router.register(r'users', api_views.UserListSet)
    router.register(r'articles', api_views.ArticleListSet)
    router.register(r'tags', api_views.TagListSet)
    router.register(r'categorys', api_views.CategoryListSet)
#
# sitemaps = {
#     'articles': ArticleSitemap,
#     'tags': TagSitemap,
#     'categories': CategorySitemap
# }

urlpatterns = [
    # url(r'^tinymce/', include('tinymce.urls')),
    # url(r'mdeditor/', include('mdeditor.urls')),
    url(r'^admin/', admin.site.urls),
    # 用户user
    url(r'^accounts/', include(('user.urls','user'), namespace='accounts')),


    url('', include(('storm.urls','blog'), namespace='blog')),  # blog

    url(r'^comment/', include(('comment.urls','comment'), namespace='comment')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

apps/user/urls.py
from django.conf.urls import url
from django.urls import path

from .views import Login_view, get_valid_img,index,profile_view,\
    logout_view,change_profile_view,register_view,change_pwd_view,change_email_view

urlpatterns = [

    url(r'^login/$', Login_view.as_view(), name='login'),
    url(r'^index/$', index, name='index'),
    url(r'^logout', logout_view, name='logout'),
    url(r'^register/$', register_view, name='register'),
    url(r'^profile/$', profile_view, name='profile'),
    # path('profile/',profile_view,name='profile'),
    url(r'^profile/change/$', change_profile_view, name='change_profile'),
    url(r'^get_valid_img/$', get_valid_img, name='get_valid_img'),
    # url(r'^user_register/$',User_Register.as_view(),name='user_register'),
    url(r'^change_pwd/$',change_pwd_view,name='change_pwd'),
    url(r'^change_email/$',change_email_view,name='change_email'),


]

apps/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


# Create your models here.

# 继承 AbstractUser ，django 自带用户类，扩展用户个人网站字段，用户头像字段
class Ouser(AbstractUser):
    # nid = models.AutoField(primary_key=True)
    nickname = models.CharField(verbose_name="昵称", max_length=32,default='匿名')
    # telephone = models.CharField(max_length=11, null=True, unique=True)

    link = models.URLField('个人网址', blank=True, help_text='提示：网址必须填写以http开头的完整格式')
    # 用户头像字段
    avatar = ProcessedImageField(
        upload_to='avatar/%Y/%m/%d',
        default='avatar/default.png',
        verbose_name='头像',
        processors=[ResizeToFill(80, 80)]
    )

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username

templates/oauth/change_email.html
{% extends 'account/base.html' %}
{% load static %}

{% block title %}
    <title>修改邮箱</title>
{% endblock %}

{% block main %}
    <div class="jq22-container" style="padding-top:100px">
        <div class="login-wrap">
            <div class="element-main">
                <div class="login-html">
                    <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1"
                                                                                             class="tab">修改邮箱</label>
                    <div class="login-form">
                        <form>
                            {% csrf_token %}
                            <div class="">
                                <div class="group">
                                    <label for="old_email" class="label" style="color: white;font-size:15px">
                                        旧邮箱<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="text" class="input" id="old_email"
                                               value="{{ request.user.email }}">
                                        {#                                                                <span class="error pull-right"></span>#}
                                    </div>
                                </div>
                                <div class="group">
                                    <label for="email" class="label" style="color: white;font-size:15px">
                                        新邮箱<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="text" class="input" id="email" placeholder="新邮箱">
                                        <span class="error pull-right"> </span>
                                    </div>
                                </div>

                                <div class="group">
                                    <input type="button" class="button" id="sub_change" value="提交">
                                </div>

                            </div>
                            <div class="foot-lnk">
                                <a href="{% url 'accounts:profile' %}">返回</a>
                            </div>
                        </form>
                        {#                        <form id="change_form" style="margin-top: 20px">#}
                        {#                            {% csrf_token %}#}
                        {#                            <div class="form-group">#}
                        {#                                <label>邮箱：</label>#}
                        {#                                <input type="text" value="{{ request.user.email }}" class="form-control" id="email">#}
                        {#                                <span class="error pull-right"></span>#}
                        {#                            </div>#}
                        {##}
                        {#                            <input type="button" value="提交" class="btn btn-info" id="sub_change">#}
                        {#                        </form>#}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--element end here-->
    <script type="text/javascript">
        $("#sub_change").click(function () {
            var email = $("#email").val();
            var formdata = new FormData();
            formdata.append("email", email);
            formdata.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

            $.ajax({
                url: "",
                type: "post",
                contentType: false,
                processData: false,
                data: formdata,
                success: function (data) {
                    console.log(data);
                    if (data.user) {
                        alert("邮箱更改成功");
                        location.href = '{% url 'accounts:profile' %}';
                    } else {
                        console.log(data.msg);
                        $(".error").html("邮箱已经被注册！").css("color", "red")
                        {#$("#email+ span").html(data.msg)#}
                        setTimeout(function () {
                            $(".error").html(' ');
                        }, 2000)
                    }
                }
            })

        })

    </script>


{% endblock %}

templates/oauth/change_profile.html
{#{% extends 'account/base.html' %}#}
{#{% load static %}#}
{#{% load oauth_tags %}#}
{#{% block title %}#}
{#<title>修改资料</title>#}
{#{% endblock %}#}
{##}
{##}
{#<!--主要内容块-->#}
{#{% block main %}#}
{#<main>#}
{#<div class="container">#}
{#    <div class="row">#}
{#        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">#}
{#            <div class="card rounded-0 px-3 px-lg-4">#}
{#                <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">修改资料</h3></div>#}
{#                <div class="card-body">#}
{#                    <form class="change_profile" method="post" enctype="multipart/form-data"{% get_user_data request.session.uid as user %} action="/accounts/profile/change/">#}
{#                        <div id="div_id_link" class="form-group">#}
{#                            <label for="id_link" class="form-control-label ">个人网址</label>#}
{#                            <div class="">#}
{#                                <input type="url" name="link" maxlength="200" class="urlinput form-control" id="id_link" />#}
{#                                <small id="hint_id_link" class="text-muted">提示：网址必须填写以http开头的完整形式</small>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div id="div_id_avatar" class="form-group">#}
{#                            <label for="id_avatar" class="form-control-label  requiredField">#}
{#                                头像<span class="asteriskField">*</span>#}
{#                            </label>#}
{#                        <div class="">目前: <a href="/media/{{ user.avatar }}">/media/{{ user.avatar }}</a><br />#}
{#                修改:#}
{#                            <input type="file" name="avatar" class="clearablefileinput" id="id_avatar" />#}
{#                        </div>#}
{#                        </div>#}
{#                        <button class="btn btn-info btn-sm rounded-0" type="submit">更新资料</button>#}
{#                    </form>#}
{#                </div>#}
{#                <div class="text-center mb-5" id="social-login">#}
{#                    <div class="login-title"><span>更多操作</span></div>#}
{#                    <div class="more-link mt-3">#}
{#                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/accounts/profile/">查看资料</a>#}
{#                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/">返回首页</a>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#</main>#}
{#{% endblock %}#}
{% load static %}
{% load oauth_tags %}
<html lang="en">
<head>
    <style>
        button {
            width: 200px; /*设置按钮宽度*/
            height: 30px; /*设置按钮高度*/
            color: white; /*字体颜色*/
            background-color: #b9def0; /*按钮背景颜色*/
            border-radius: 3px; /*让按钮变得圆滑一点*/
            border-width: 0; /*消去按钮丑的边框*/
            margin: 0;
            outline: none; /*取消轮廓*/
            font-family: KaiTi, serif; /*字体设置为楷体*/
            font-size: 17px; /*设置字体大小*/
            text-align: center; /*字体居中*/
            cursor: pointer; /*设置鼠标箭头手势*/
        }

        button:hover { /*鼠标移动时的颜色变化*/
            background-color: antiquewhite;
        }
    </style>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'images/picture.ico' %}" type="image/x-icon"/>
    <title>修改资料</title>
    <!-- favicon.ico
      ================================================== -->
    {#    <link rel='shortcut icon' href="/media/avatar/default.png" type="image/x-icon"/>#}

    <link rel="stylesheet" type="text/css" href="">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/bootstrap-3.3.7/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/user_profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/change_profile.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text:400,700,700i|Josefin+Sans:700" rel="stylesheet">
    {#    <link href="{% static 'Myapp/assets/css/main.css' %}" rel="stylesheet">#}
    {#<link rel="icon" href="{% static 'Myapp/assets/images/logo.png' %}">#}
    {#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">#}

</head>

<body class="mainbody_change">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div style="margin:0 auto;width: 750px;height: 400px;border:10px solid #bbe1f1 ;background:#eefaff">
        <div class="row home">
            {#            <div >#}
            {#                <div style="position: relative; top: 40px;left:50px ;width: 200px;height: 200px">#}
            {#                    <img id="avatar_img" src="/media/{{ user.avatar }}" alt="{{ user.username }}" width="200" height="200">#}
            {#                </div>#}
            {#                <!-- avatar -->#}
            {#                <div style="position: relative; top: 100px;left:50px;">#}
            {#                    <button><input type="file" name="avatar" id="avatar" class="btn"></button>#}
            {#                </div>#}
            {#            </div>#}
            <div class="aui-info">
                <img src="/media/{{ request.user.avatar }}" id="avatar_img" width="200" height="200">
{#                <input type="file" accept="image/*" id="avatar" name="file">#}
                  <input type="file" id="avatar" name="avatar">
{#                       onchange="upload('#file-txz', '#img-txz');" class="fileInput" value=""/>#}
            </div>

            <div style="position: relative;top: 70px;left:130px;text-align: center">
                <div>
                    <p class="home-description">
                        账号：<label>
                        <input name="username" type="text" value="{{ user.username }}">
                    </label>
                    </p>
                    <p class="home-description">
                        邮箱：<label>
                        <input name="email" type="text" value="{{ user.email }}">
                    </label>
                    </p>
                    {#                    <p class="home-description">#}
                    {#                        地址：<label>#}
                    {#                        <input name="address" type="text" value="{{ userinfo.address }}">#}
                    {#                    </label>#}
                    {#                    </p>#}
                    {#                    <p class="home-description">#}
                    {#                        简介：<label>#}
                    {#                        <input name="detail" type="text" value="{{ userinfo.detail }}">#}
                    {#                    </label>#}
                    {#                    </p>#}
                </div>
                <p style="position: absolute; left: 130px;top: 220px;" class="center">
                  <input type="button" value="提交" class="btn btn-info" id="sub_change">
                </p>
            </div>
            <a href='{% url 'accounts:profile' %}' class="link_question">&nbsp&nbsp&nbsp&nbsp返回信息卡</a>
        </div>
    </div>

    {#    <script src="{% static 'Myapp/assets/js/script.js' %}"></script>#}
</form>

<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
<script>

    //头像预览功能
    $("#avatar").change(function () {
        var choose_file = $(this)[0].files[0];
        var reader = new FileReader();
        reader.readAsDataURL(choose_file)

        reader.onload = function () {
            $("#avatar_img").attr("src", this.result);
        }
    });

    $("#sub_change").click(function (){
        var formdata = new FormData();
        formdata.append("avatar",$("#avatar")[0].files[0]);
        formdata.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val())
        $.ajax({
            utl:"",
            type:"post",
            contentType:false,
            processData:false,
            data:formdata,
            success:function (data){
                if(data.user){
                    alert('头像更改成功！');
                    location.href = '{% url 'accounts:index' %}';
                }

            }
        })

    })


</script>




</body>
</html>

templates/oauth/change_pwd.html
{% extends 'account/base.html' %}
{% load static %}

{% block title %}
    <title>修改密码</title>
{% endblock %}

{% block main %}


    <div class="jq22-container" style="padding-top:100px">
        <div class="login-wrap">
            {#	<h2>密码重置</h2>#}
            <div class="element-main">
                {#		<h1>修改您的密码</h1>#}
                {#		<p> 切勿将您的密码告诉他人.</p>#}
                <div class="login-html">
                    <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1"
                                                                                             class="tab">修改密码</label>
                    <div class="login-form">
                        <form>
                            {% csrf_token %}
                            <div class="">
                                <div  class="group">
                                    <label for="pwd" class="label" style="color: white;font-size:15px">
                                        新密码<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="text" class="input" id="pwd" placeholder="新密码">
                                    </div>
                                </div>

                                <div  class="group">
                                    <label for="re_pwd" class="label" style="color: white;font-size:15px">
                                        确认新密码<span class="asteriskField">*</span>
                                    </label>
                                    <div class="">
                                        <input type="password" class="input" id="re_pwd" placeholder="确认新密码">
                                        <span class="error pull-right"> </span>
                                    </div>
{#                                    <span class="error pull-right"></span>#}
                                </div>
                                <div class="group">
                                    <input type="button" class="button" id="sub_change" value="提交">
                                </div>

                            </div>
                             <div class="foot-lnk">
                                    <a href="{% url 'accounts:profile' %}">返回</a>
                                    {#                                <input type="button" value="登录1" class="btn btn-primary pull-right login_btn">#}
                             </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--element end here-->
    <script type="text/javascript">
        $("#sub_change").click(function () {
            var pwd = $("#pwd").val();
            var re_pwd = $("#re_pwd").val();
            if (pwd !== re_pwd) {
                $(".error").html("两次密码不一致").css("color", "red")
                setTimeout(function () {
                    $(".error").html(' ');
                }, 2000)
                return
            }
            $.ajax({
                url: "",
                type: "post",
                data: {
                    "pwd": pwd,
                    "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val(),
                },
                success: function (data) {
                    console.log(data);
                    if (data.user) {
                        alert("更改密码成功");
                        location.href = '{% url 'accounts:login' %}';

                    } else {
                        $("#pwd").html(data.msg)
                    }
                }
            })
        })
    </script>




{% endblock %}

templates/oauth/profile.html
{#{% extends 'account/base.html' %}#}
{#{% load static %}#}
{#{% load oauth_tags %}#}
{##}
{#{% block title %}#}
{#    <title>个人中心</title>#}
{#{% endblock %}#}
{##}
{##}
{#<!--主要内容块-->#}
{#{% block main %}#}
{#    <main>#}
{#        <div class="container">#}
{#            <div class="row">#}
{#                <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">#}
{#                    <div class="card rounded-0 px-3 px-lg-4">#}
{#                        <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">个人资料</h3></div>#}
{#                        <div class="card-body">#}
{#                            <ul class="list-group">#}
{#                                <li class="list-group-item text-center border-0" id="profile-avatar">#}
{#                                    {% get_user_data request.session.uid as user %}#}
{##}
{#                                    {% if user %}#}
{##}
{#                                        <img class="avatar" src="/media/{{ user.avatar }}" alt="{{ user.username }}">#}
{##}
{#                                        </li>#}
{#                                        <li class="list-group-item ml-5 border-0">#}
{#                                            <span class="font-weight-bold">用户名：</span>#}
{#                                            <span>{{ user.username }}</span>#}
{#                                        </li>#}
{#                                        <li class="list-group-item ml-5 border-0">#}
{#                                            <span class="font-weight-bold">邮&emsp;箱：</span>#}
{#                                            <span>{{ user.email }}</span>#}
{#                                        </li>#}
{#                                        <li class="list-group-item ml-5 border-0">#}
{#                                            <span class="font-weight-bold">网&emsp;址：</span>#}
{#                                            <span>{{ user.link }}</span>#}
{#                                        </li>#}
{#                                        </ul>#}
{#                                        </div>#}
{#                                        <div class="text-center mb-5" id="social-login">#}
{#                                            <div class="more-link mt-3">#}
{#                                                <a class="btn btn-info btn-sm rounded-0 mx-3"#}
{#                                                   href="/accounts/profile/change/">修改资料</a>#}
{#                                                <a class="btn btn-info btn-sm rounded-0 mx-3" href="/">返回首页</a>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                    {% endif %}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </main>#}
{#{% endblock main %}#}


{% load oauth_tags static %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ user.username }}的个人主页</title>
    <link rel="stylesheet" href="/static/css/user_profile.css?v=udTRe6JYfbH-bS6xgPAkC2x_TCfJy7-irgBBYrP28yA"/>
    <link rel="icon" href="{% static 'images/picture.ico' %}" type="image/x-icon"/>
</head>
<body class="mainbody">
<div id="user_profile_block">
    <table>
        <tbody>
        <tr>
            <td valign="top">
                <div class="user_avatar">
                    {#                    <img src="//pic.cnblogs.com/avatar/2179358/20210307193921.png" alt="水墨点点的头像" class="img_avatar"><br>#}
                    <img class="avatar" src="/media/{{ request.user.avatar }}" alt="{{ user.username }}" width="250px" height="200px">
                    <table class="user_profile_nav_block">
                        <tbody>
                        <tr>
                            <td>
                                <ul class="avatar_nav_block" id="avatar_opt_nav">
                                    <li><a href="/accounts/profile/change/" class="link_modify_info">修改信息</a></li>
                                    <li><a href='{% url 'accounts:change_pwd' %}' class="link_question">修改密码</a></li>
                                    <li><a href='{% url 'accounts:change_email' %}' class="link_question">修改邮箱</a></li>
                                    <li><a href='http://127.0.0.1:8000/' class="link_question">返回主页</a></li>


                                </ul>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </td>
            <td valign="top">
                <div>
                    <h1 class="display_name">
                        {{ user.username }}的信息卡
                    </h1>
                    <div>
                        <ul id="user_profile" class="user_profile">
                            <li id="li_remark" style="display:none"><span class="text_gray">备注名称：</span><span
                                    id="remarkId"></span></li>
                            <li><span class='text_gray' title='账户ID'>爱好:</span><span>ACG(二次元就是个梦，梦里啥都有，取决于你想要什么)</span></li>
                            <li><span class='text_gray'>二次元浓度:</span><span>经典中二病</span></li>
                            <li><span class='text_gray'>创站日期:</span><span>2021-4-1</span></li>
                            <li><span class='text_gray'>目标:</span><span>发现生活中的美好，技术宅拯救世界</span></li>
                            <li><span class='text_gray'>愿望:</span><span>世界和平</span></li>
                            {#                            <li><span class='text_gray'>我的主页:</span><a id='blog_url'#}
                            {#                                                                     href='http://127.0.0.1:8000/'#}
                            {#                                                                     class='gray' target='_blank'>http://127.0.0.1:8000/</a>#}

                        </ul>
                    </div>
                    <div class="text_gray" style="padding-top: 10px;">
                        <div class="data_count_block" style="padding: 0px 0 15px;">
                            {#                                <div class="data_left">#}
                            {#                                    <div class="follow_count"><a id="following_count" href="/u/wjymyblog/followees/">0</a></div>#}
                            {#                                    <a href="/u/wjymyblog/followees/">关注</a>#}
                            {#                                </div>#}
                            {#                                <div class="data_right">#}
                            {#                                    <div class="follow_count"><a id="follower_count" href="/u/wjymyblog/followers/">0</a></div>#}
                            {#                                    <a href="/u/wjymyblog/followers/">粉丝</a>#}
                            {#                                </div>#}
                            <div class="clear">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="clear">
                </div>
                <br>
                <div class="user_intro">
                </div>
            </td>
        </tr>
        </tbody>
    </table>
    <br>
</div>

</body>
</html>