Myblog1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from rest_framework.routers import DefaultRouter

from storm.sitemaps import ArticleSitemap, TagSitemap, CategorySitemap
from api import views as api_views
if settings.API_FLAG:
    router = DefaultRouter()
    router.register(r'users', api_views.UserListSet)
    router.register(r'articles', api_views.ArticleListSet)
    router.register(r'tags', api_views.TagListSet)
    router.register(r'categorys', api_views.CategoryListSet)
#
# sitemaps = {
#     'articles': ArticleSitemap,
#     'tags': TagSitemap,
#     'categories': CategorySitemap
# }

urlpatterns = [
    # url(r'^tinymce/', include('tinymce.urls')),
    # url(r'mdeditor/', include('mdeditor.urls')),
    url(r'^admin/', admin.site.urls),
    # 用户user
    url(r'^accounts/', include(('user.urls','user'), namespace='accounts')),


    url('', include(('storm.urls','blog'), namespace='blog')),  # blog

    url(r'^comment/', include(('comment.urls','comment'), namespace='comment')),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

apps/storm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from .views import *

urlpatterns = [
    url(r'404/$', Page_Not_Found.as_view(), name='notfound'),
    url(r'^$', IndexView.as_view(template_name='index.html'), name='index'),  # 主页，自然排序
    url(r'^link/$', LinkView, name='link'),  # 申请友情链接
    url(r'^category/message/$', MessageView, name='message'),
    url(r'^category/about/$', AboutView, name='about'),

    url(r'^category/exchange/$', ExchangeView, name='exchange'),

    # 分类页面
    url(r'^category/(?P<bigslug>.*?)/(?P<slug>.*?)', IndexView.as_view(template_name='content.html'), name='category'),
    # 归档页面
    url(r'^date/(?P<year>\d+)/(?P<month>\d+)/$', IndexView.as_view(template_name='archive.html'), name='date'),
    # 标签页面
    url(r'^tag/(?P<tag>.*?)/$', IndexView.as_view(template_name='content.html'), name='tag'),
    # 文章详情页面
    url(r'^article/(?P<slug>.*?)/$', DetailView.as_view(), name='article'),
    # 全文搜索
    url(r'^search/$', MySearchView.as_view(), name='search'),
    # 喜欢
    url(r'^love/$', LoveView, name='love'),

    url(r'^(?P<username>\w+)/backend/$', backend),
    url(r'^(?P<username>\w+)/backend_add_article/$', backend_add_article, name='add_article'),
    url("backend/(\d+)/delete_article/$", delete_article, name='delete_article'),
    url("backend/(\d+)/edit_article/$", edit_article, name='edit_article'),

]

apps/user/urls.py
from django.conf.urls import url
from django.urls import path

from .views import Login_view, get_valid_img,index,profile_view,\
    logout_view,change_profile_view,register_view,change_pwd_view,change_email_view

urlpatterns = [

    url(r'^login/$', Login_view.as_view(), name='login'),
    url(r'^index/$', index, name='index'),
    url(r'^logout', logout_view, name='logout'),
    url(r'^register/$', register_view, name='register'),
    url(r'^profile/$', profile_view, name='profile'),
    # path('profile/',profile_view,name='profile'),
    url(r'^profile/change/$', change_profile_view, name='change_profile'),
    url(r'^get_valid_img/$', get_valid_img, name='get_valid_img'),
    # url(r'^user_register/$',User_Register.as_view(),name='user_register'),
    url(r'^change_pwd/$',change_pwd_view,name='change_pwd'),
    url(r'^change_email/$',change_email_view,name='change_email'),


]

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/archive.html
{%extends 'base_right.html'%}
{% load comment_tags %}
{% block title %}ACG丨文章归档{% endblock title %}
{% block description %}
    <meta name="description" content="文章按照月份分类归档。"/>
    {% endblock description %}
{% block keywords %}
    <meta name="keywords" content="网络爬虫工具,python,http代理,scrapy爬虫,爬虫代理ip,python为什么叫爬虫,python爬虫怎么赚钱，ACG，二次元"/>
    {% endblock keywords %}
{%block body%}
	<div class="content-wrap">
	    <div class="content">
		    <header class="archive-header">
			    <h1><i class="fa fa-folder-open"></i>  &nbsp;分类：福利专区  <a title="订阅福利专区" target="_blank" href="{% url 'blog:category' resources '' %}"><i class="rss fa fa-rss"></i></a></h1>
					</header>
        {% for article in page_obj %}
				<article class="excerpt">
	<header><a class="label label-important" href="/category/{{ article.category.bigcategory.name }}/{{ article.category.name|lower }}">{{ article.category.name }}<i class="label-arrow"></i></a><h2><a target="_blank" href="/article/{{ article.slug }}" title="{{ article.title }}">{{ article.title }} </a></h2>
	</header>
	<div class="focus"><a target="_blank" href="/article/{{ article.slug }}"><img class="thumb" width="200" height="123" src="{{ article.img_link }}" alt="{{ article.title }}" /></a></div>
			<span class="note"> {{ article.summary }}</span>
<p class="auth-span">
		<span class="muted"><i class="fa fa-user"></i> <a href="/author/{{ article.author }}">{{ article.author }}</a></span>
		<span class="muted"><i class="fa fa-clock-o"></i> {{ article.create_date|date:'Y-m-d'}}</span>	<span class="muted"><i class="fa fa-eye"></i> {{ article.views }}浏览</span>	<span class="muted"><i class="fa fa-comments-o"></i> <a target="_blank" href="/article/{{ article.slug }}#comments">{% get_comment_count article.id  article.id%}评论</a></span><span class="muted">
<a href="javascript:;" data-action="ding" data-id="455" id="Addlike" class="action"><i class="fa fa-heart-o"></i><span class="count">{{ article.love }}</span>喜欢</a></span></p>
</article>
        {% empty %}
                <div class="no-post">当前分类下还没有发布的文章！</div>
        {% endfor %}
{% if is_paginated %}
            <div class="pagination">
                <ul>
                    {% if first %}
                        <li><a href="?page=1">1</a></li>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                        {% for i in left %}
                            <li class="prev-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                    {% endif %}
                    <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                    {% if right %}
                        {% for i in right %}
                            <li class="next-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if right_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
        </div>
    </div>
{%endblock body%}

templates/article.html
{% extends 'base_right.html' %}
{% load blog_tags static %}
{% block title %}{{ object.title }}{% endblock title %}

{% block description %}
    <meta name="description" content="{{ object.summary }}"/>
{% endblock description %}
{% block keywords %}
    <meta name="keywords" content="{% get_article_keywords object %}"/>
{% endblock keywords %}

{% block body %}
    <div class="content-wrap">
        <div class="content">
            <div class="breadcrumbs">
                <a title="返回首页" href="/"><i class="fa fa-home"></i></a><small>></small>
                <a href="/category/{{ object.category.bigcategory.slug }}">{{ object.category.bigcategory.name }}</a>
                <small>></small>
                <a href="/category/{{ object.category.bigcategory.slug }}/{{ object.category.name|lower }}">{{ object.category.name }}</a>
                <small>></small> <span class="muted">{{ object.title }}</span>
            </div>
            <header class="article-header">
                <h1 class="article-title"><a href="/article/{{ object.slug }}">{{ object.title }}</a></h1>
                <div class="meta">
                    <span id="mute-category" class="muted">
                        <i class="fa fa-list-alt"></i>
                        <a href="category/technique/{{ object.category.name|lower }}"> {{ object.category.name }}</a>
                    </span>
                    <span class="muted">
                        <i class="fa fa-user"></i>
                        <a href="/author/{{ object.author.name }}">{{ object.author }}</a>
                    </span>
                    <time class="muted"><i class="fa fa-clock-o"></i> {{ object.create_date|date:'y-m-d' }}</time>
                    <span class="muted"><i class="fa fa-eye"></i> {{ object.views }}浏览</span>
                    <span class="muted">
                        <i class="fa fa-comments-o"></i>
                        <a href="/article/{{ object.slug }}#respond">0评论</a>
                    </span>
                </div>
            </header>
            <article class="article-content">
                {{ article.body|safe }}
                <p>转载请注明：
                    <a href="{% url 'blog:article' object.slug %}">二十三画生</a> &raquo;
                    <a href="{% url 'blog:article' object.slug %}">{{ object.title }}</a>
                </p>

                <div class="article-social">
                    <a href="javascript:;" data-action="ding" data-id="{{ object.id }}" id="Addlike" class="action">
                        <i class="fa fa-heart-o"></i>喜欢 (<span class="count">{{ object.loves }}</span>)
                    </a>
                    <span class="or">or</span>
                    <span class="action action-share bdsharebuttonbox"><i class="fa fa-share-alt"></i>分享 (
                                <span class="bds_count" data-cmd="count" title="累计分享0次">0</span>)
                                <div class="action-popover">
                                    <div class="popover top in">
                                        <div class="arrow"></div>
                                        <div class="popover-content">
                                            <a href="#" class="sinaweibo fa fa-weibo" data-cmd="tsina"
                                               title="分享到新浪微博"></a>
                                            <a href="#" class="bds_qzone fa fa-star" data-cmd="qzone"
                                               title="分享到QQ空间"></a>
                                            <a href="#" class="bds_github fa fa-github" data-cmd="github"
                                               title="分享到github"></a>
                                            <a href="#" class="bds_renren fa fa-qq" data-cmd="sqq" title="分享到QQ好友"></a>
                                            <a href="#" class="bds_renren fa fa-twitter" data-cmd="renren"
                                               title="分享到推特网"></a>
                                            <a href="#" class="bds_weixin fa fa-weixin" data-cmd="weixin"
                                               title="分享到微信"></a>
                                            <a href="#" class="bds_renren fa fa-facebook" data-cmd="weixin"
                                               title="分享到facebook"></a>
                                            <a href="#" class="bds_more fa fa-ellipsis-h" data-cmd="more"></a>
                                        </div>
                                    </div>
                                </div>
                            </span>
                </div>
            </article>
        </div>
        <footer class="article-footer">
            <!--文章标签-->
            <div class="article-tags">
                <i class="fa fa-tags"></i>
                {% get_article_tag object.id as tags %}
                {% for tag in tags %}..
                    <a href="{% url 'blog:tag' tag.name %}" rel="tag">{{ tag.name }}</a>
                {% endfor %}
            </div>
            <!--文章标签结束-->

        </footer>
        <!--推荐文章-->
        <nav class="article-nav">
                        <span class="article-nav-prev">
                            <i class="fa fa-angle-double-left"></i>
                            {% get_article_previous object.id as article_previous %}
                            <a href="{% url 'blog:article' article_previous.slug %}"
                               rel="prev">{{ article_previous.title }}</a>
                        </span>
            <span class="article-nav-next">
                            {% get_article_next object.id as article_next %}
                            <a href="{% url 'blog:article' article_next.slug %}"
                               rel="prev">{{ article_next.title }}</a>
                            <i class="fa fa-angle-double-right"></i>
                        </span>
        </nav>

        <div class="related_top">
            <div class="related_posts">
                <ul class="related_img">
                    {% get_category_article as  category_article %}
                    {% for article in category_article.article_2 %}
                        <li class="related_box">
                            <a href="{% url 'blog:article' article.slug %}" title="{{ article.title }}"
                               target="_blank">
                                <img src="{{ article.img_link }}" alt="{{ article.title }}" width="50%" ><br>
                                <span class="r_title">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ article.title }}
                                  </span></a>
                        </li>
                    {% endfor %}
                </ul>

                <div class="relates">
                    <ul>
                        {% for article in category_article.article_8 %}
                            <li>
                                <i class="fa fa-minus"></i>
                                <a href="{% url 'blog:article' article.slug %}">{{ article.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>

        {% include 'comment_list.html' %}
    </div>
    </div>
{% endblock body %}

templates/base_right.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags static %}


{% block right %}
    <aside class="sidebar">
        <div class="widget widget_text">
            <div class="textwidget">
                <div class="social">

                    <a href="https://weibo.com/5743831893/profile?rightmod=1&wvr=6&mod=personinfo"
                       rel="external nofollow" title="新浪微博" target="_blank"><i class="sinaweibo fa fa-weibo"></i></a>

                    <a href="tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=1964576235&website=www.oicqzone.com"
                       rel="external nofollow" title="QQ" target="_blank"><i class="tencentweibo fa fa-qq"></i></a>

                    <a href="" class="weixin"><i class="weixins fa fa-weixin"></i>
                        <div class="weixin-popover">
                            <div class="popover bottom in">
                                <div class="arrow"></div>
                                <div class="popover-title"></div>
                                <div class="popover-content"><img src="{% static 'images/gerenweixin.png' %}"></div>
                            </div>
                        </div>
                    </a>
                    <a href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=vuzezrwkmv@qq.com"
                       rel="external nofollow" title="Email"
                       target="_blank"><i class="email fa fa-envelope-o"></i></a>
                    <a href="/404/" rel="external nofollow" target="_blank" title="订阅本站"><i
                            class="rss fa fa-rss"></i></a>
                </div>
            </div>
        </div>

        <div class="widget widget_metaslider_widget">
            <!--热门专题-->
            <div class="title"><h2>热门专题</h2></div><!-- meta slider -->
            <div style="width: 100%;" class="metaslider metaslider-nivo metaslider-2698 ml-slider meta-slider">
                <div id="metaslider_container_2698">
                    <div class='slider-wrapper theme-bar'>
                        <div class='ribbon'></div>
                        <div id='metaslider_2698' class='nivoSlider'>
                            {% get_carousel_right as carousels %}
                            {% for carousel in carousels %}
                                <a href="{{ carousel.url }}" target="_blank">
                                    <img src="{{ carousel.img_url }}" height="300" width="320"
                                         data-title="{{ carousel.content }}"
                                         title="{{ carousel.title }}" alt="{{ carousel.title }}"
                                         class="slider-2698 slide-1720"/>
                                </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <!--热门专题结束-->

                <script type="text/javascript">
                    var metaslider_2698 = function ($) {
                        $('#metaslider_2698').nivoSlider({
                            boxCols: 7,
                            boxRows: 5,
                            pauseTime: 3000,
                            effect: "random",
                            controlNav: false,
                            directionNav: true,
                            pauseOnHover: true,
                            animSpeed: 600,
                            prevText: "&lt;",
                            nextText: "&gt;",
                            slices: 15,
                            manualAdvance: false
                        });
                    };
                    var timer_metaslider_2698 = function () {
                        var slider = !window.jQuery ? window.setTimeout(timer_metaslider_2698, 100) : !jQuery.isReady ? window.setTimeout(timer_metaslider_2698, 1) : metaslider_2698(window.jQuery);
                    };
                    timer_metaslider_2698();
                </script>
            </div>
            <!--// meta slider-->
        </div>
        <!--广告位-->
        <div class="widget widget_text">
            <div class="textwidget">
                {#                    <a href="/"><img style="width:100%" src="{% static 'images/weixin.png' %}"/></a>#}
            </div>
        </div>
        <!--广告位结束-->
        <div class="widget widget_archive">

            <!--文章归档-->
            <div class="title"><h2>月份归档</h2></div>
            {% get_data_date as data_date %}
            <ul>
                {% if data_date %}
                    {% for date in data_date %}
                        <li><a href='{% url 'blog:date' date|date:'Y' date|date:'m' %}'>{{ date|date:'Y-m' }}</a></li>
                    {% endfor %}
                {% else %}
                    <div>近期没有发表过文章</div>
                {% endif %}
            </ul>
        </div>
        <!--文章归档结束-->

        <!--猜你喜欢-->
        <div class="widget d_postlist">
            <div class="title"><h2>猜你喜欢</h2></div>
            <ul>
                {% get_article_list 'loves' 6 as hot_tag %}
                {% for hot in hot_tag %}
                    <li>
                        <a href="/article/{{ hot.slug }} " title="{{ hot.title }}">
                            <span class="thumbnail"><img src="{{ hot.img_link }}" alt="{{ hot.title }}"/></span>
                            <span class="text">{{ hot.title }}</span>
                            <span class="muted">{{ hot.create_date|date:'Y-m-d' }}</span>
                            {#                            <span class="muted">{{ hot.loves }}喜欢</span>#}
                            <span class="muted"><i class="fa fa-heart-o"></i><span class="count">{{ hot.loves }}</span>喜欢</span>

                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <!--猜你喜欢结束-->

        <!--标签云-->
        <div class="widget d_tag">
            <div class="title"><h2>标签云集</h2></div>
            <div class="d_tags">
                {% get_tag_list as tags %}
                {% for tag in tags %}
                    <a title="{{ tag.total_num }}个话题" href="{% url 'blog:tag' tag.name %}">{{ tag.name }}
                        ({{ tag.total_num }})</a>
                {% endfor %}
            </div>
        </div>
        <!--标签云结束-->

        <!--友情链接-->
        <div class="widget widget_links">
            <div class="title"><h2>动漫网站</h2></div>
            {% get_friends as friends %}
            <ul class='xoxo blogroll'>
                {% if friends %}
                    {% for friend in friends %}
                        <li><a href="{{ friend.link }}" target="_blank">{{ friend.name }}</a></li>
                    {% endfor %}
                {% else %}
                    <div class="">
                        <a href="https://www.bilibili.com/">&nbsp;bilibili</a>
                        <a href="https://www.acfun.cn/">&nbsp;AcFUN</a>
                        <a href="http://www.imomoe.ai/">&nbsp;樱花动漫</a>
                        <a href="https://news.dmzj.com/">&nbsp;动漫之家</a>
                        <a href="http://www.fengchedm.com/">&nbsp;风车动漫</a>
                    </div>
                {% endif %}
            </ul>
        </div>
        <!--友情链接结束-->

        <!--精品推荐-->
        <div class="widget widget_text">
            <div class="title"><h2>游戏推荐</h2></div>
            <div class="text widget">
                <a href="https://baike.baidu.com/item/%E5%A1%9E%E5%B0%94%E8%BE%BE%E4%BC%A0%E8%AF%B4/4163802?fr=aladdin">&nbsp;&nbsp;&nbsp;塞尔达系列</a>
                <a href="https://store.steampowered.com/">&nbsp;&nbsp;&nbsp;steam平台</a>
            </div>
        </div>

        <!--精品推荐结束-->
        <div class="widget widget_text">
            <div class="title"><h2>参考网站</h2></div>
            <div class="text widget">
                &nbsp;&nbsp;&nbsp; <a href="https://stormsha.com/category/technique/">stormsha的个人博客</a><br>
                <br>
                <a href="https://tendcode.com/">&nbsp;&nbsp;&nbsp;&nbsp;Tendcode的个人博客</a><br>
                <br>
                <a href="https://cuiqingcai.com/">&nbsp;&nbsp;&nbsp;&nbsp;崔庆才的个人博客</a><br>
            </div>
        </div>


        <!--live2d_test-->
        <div class="waifu">
            <div class="waifu-tips"></div>
            <canvas id="live2d" width="280" height="250" class="live2d"></canvas>
            <div class="waifu-tool">
                <span class="fui-home"></span>
                <span class="fui-chat"></span>
                <span class="fui-eye"></span>
                <span class="fui-user"></span>
                <span class="fui-photo"></span>
                <span class="fui-info-circle"></span>
                <span class="fui-cross"></span>
            </div>
        </div>

        <script src="/static/assets/waifu-tips.js"></script>
        <script src="/static/assets/live2d.js"></script>
        <script type="text/javascript">initModel("/static/assets/")</script>

        <!--aplayer_test-->
        <div class="aplayer"
             data-id="634900247"
             data-fixed="true"
             data-server="netease"
             data-volume="0.4"
             data-type="playlist">
        </div>

        <script src="/static/Aplayer/Meting.min.js"></script>

    </aside>
{% endblock right %}

templates/content.html
{% extends 'base_right.html' %}
{% load comment_tags blog_tags %}

{% block description %}
    <meta name="description" content="{% get_title category as c %}{{ c.description }}"/>
{% endblock description %}
{% block keywords %}
    <meta name="keywords" content="{% get_title category as c %}{{ c.keywords }}"/>
{% endblock keywords %}
{% block title %}{% get_title category as c %}ACG丨{{ c.name }}{% endblock title %}

{% block body %}
    <div class="content-wrap">
        <div class="content">
            <header class="archive-header">
                <h1><i class="fa fa-folder-open"></i> &nbsp;分类：福利专区 <a title="订阅福利专区" target="_blank"
                                                                       href="{% url 'blog:category' resources '' %}"><i
                        class="rss fa fa-rss"></i></a></h1>
            </header>
            {% for article in page_obj %}
                <article class="excerpt">
                    <header><a class="label label-important"
                               href="/category/{{ article.category.bigcategory.name }}/{{ article.category.name|lower }}">{{ article.category.name }}<i
                            class="label-arrow"></i></a>
                        <h2><a target="_blank" href="/article/{{ article.slug }}"
                               title="{{ article.title }}">{{ article.title }} </a></h2>
                    </header>
                    <div class="focus"><a target="_blank" href="/article/{{ article.slug }}"><img class="thumb"
                                                                                                  width="200"
                                                                                                  height="123"
                                                                                                  src="{{ article.img_link }}"
                                                                                                  alt="{{ article.title }}"/></a>
                    </div>
                    <span class="note"> {{ article.summary }}</span>
                    <p class="auth-span">
                        <span class="muted"><i class="fa fa-user"></i> <a
                                href="/author/{{ article.author }}">{{ article.author }}</a></span>
                        <span class="muted"><i class="fa fa-clock-o"></i> {{ article.create_date|date:'Y-m-d' }}</span>
                        <span class="muted"><i class="fa fa-eye"></i> {{ article.views }}浏览</span> <span
                            class="muted"><i class="fa fa-comments-o"></i> <a target="_blank"
                                                                              href="/article/{{ article.slug }}#comments">{% get_comment_count article.id article.id %}评论</a></span><span
                            class="muted">
<a href="javascript:;" data-action="ding" data-id="455" id="Addlike" class="action"><i class="fa fa-heart-o"></i><span
        class="count">{{ article.love }}</span>喜欢</a></span></p>
                </article>
            {% empty %}
                <div class="no-post">当前分类下还没有发布的文章！</div>
            {% endfor %}
            {% if is_paginated %}
                <div class="pagination">
                    <ul>
                        {% if first %}
                            <li><a href="?page=1">1</a></li>
                        {% endif %}
                        {% if left %}
                            {% if left_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                            {% for i in left %}
                                <li class="prev-page"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                        {% if right %}
                            {% for i in right %}
                                <li class="next-page"><a href="?page={{ i }}">{{ i }}</a></li>
                            {% endfor %}
                            {% if right_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                        {% endif %}
                        {% if last %}
                            <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock body %}

templates/exchange.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/link.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>